import { icon } from '../components/common.js';

function brand() {
  return '<a class="portal-auth-brand" href="#/" aria-label="BestCheckout home"><span class="portal-mark">B</span><strong>BestCheckout</strong></a>';
}

function authLayout(eyebrow, title, copy, formMarkup, foot) {
  return '<div class="portal-auth"><aside class="portal-auth-aside"><div>' + brand() + '<span class="portal-auth-kicker">Checkout growth for Shopify brands</span><h1>Build a better<br/><em>way to buy.</em></h1><p>One workspace for your checkout, offers, payment connections and order performance.</p></div><div class="portal-auth-aside-proof"><span>' + icon('shield', 18) + '</span><p>Your Shopify store stays in your control. BestCheckout connects only the data it needs to run your checkout.</p></div></aside><main class="portal-auth-main"><div class="portal-auth-card"><div class="portal-auth-mobile-brand">' + brand() + '</div><span class="portal-auth-eyebrow">' + eyebrow + '</span><h2>' + title + '</h2><p>' + copy + '</p>' + formMarkup + (foot || '') + '</div></main></div>';
}

export function renderSignIn() {
  const form = '<form class="portal-form" id="portal-login-form"><label>Email<input required type="email" name="email" value="hello@lavenderlabs.co" autocomplete="email" /></label><label>Password<div class="portal-password-field"><input required type="password" name="password" value="demo-password" autocomplete="current-password" /><button type="button" aria-label="Show password">' + icon('eye', 16) + '</button></div></label><div class="portal-form-row"><label class="portal-check"><input type="checkbox" checked /> <span>Keep me signed in</span></label><button type="button" class="portal-inline-button">Forgot password?</button></div><button type="submit" class="portal-submit">Sign in ' + icon('arrow', 16) + '</button></form>';
  return authLayout('Welcome back', 'Sign in to BestCheckout', 'Manage checkout growth for your Shopify store.', form, '<p class="portal-auth-foot">New to BestCheckout? <button type="button" data-route="sign-up">Create your account</button></p>');
}

export function renderSignUp() {
  const form = '<form class="portal-form" id="portal-signup-form"><label>Work email<input required type="email" name="email" placeholder="you@company.com" autocomplete="email" /></label><label>Full name<input required type="text" name="name" placeholder="Your name" autocomplete="name" /></label><label>Password<input required type="password" name="password" placeholder="Create a password" autocomplete="new-password" /></label><label class="portal-check portal-terms"><input type="checkbox" data-signup-terms aria-describedby="signup-terms-error" /> <span>I agree to the Terms and Privacy Policy.</span></label><p id="signup-terms-error" class="portal-field-error" data-signup-terms-error role="alert" hidden>To continue, select the box to agree to the Terms and Privacy Policy.</p><button type="submit" class="portal-submit">Create account ' + icon('arrow', 16) + '</button></form>';
  return authLayout('Get started', 'Create your BestCheckout account', 'Start with your Shopify store. You can build and test before sending buyers to a new checkout.', form, '<p class="portal-auth-foot">Already have an account? <button type="button" data-route="sign-in">Sign in</button></p>');
}

export function renderConnectShopify() {
  const credentialsHelp = '<aside class="connect-credentials-help"><div><strong>Need your Client ID and Client secret?</strong><span>Open your Shopify app\'s Settings in Shopify Dev Dashboard to find both credentials.</span></div><a href="../help/#guide=connect-shopify" target="_blank" rel="noopener">View the guide ' + icon('external', 14) + '</a></aside>';
  return '<div class="connect-flow"><header class="connect-header">' + brand() + '<button type="button" class="portal-inline-button" data-action="portal-signout">Sign out</button></header><main><div class="connect-card"><span class="connect-icon">' + icon('store', 23) + '</span><span class="portal-auth-eyebrow">Shopify connection</span><h1>Connect your Shopify store</h1><p>Use the app you create in Shopify Dev Dashboard. BestCheckout uses it only to keep checkout data current and write paid orders back to Shopify.</p><form class="portal-form" id="connect-shopify-form"><label>Shopify store address<div class="portal-domain-input"><input required type="text" name="shopDomain" value="lavender-labs" /><span>.myshopify.com</span></div><small>Enter the permanent <strong>myshopify.com</strong> address, not your storefront domain.</small></label>' + credentialsHelp + '<label>Client ID<input required type="text" name="clientId" value="demo_client_id" autocomplete="off" /><small>Find this in the app\'s <strong>Settings</strong> page in Shopify Dev Dashboard.</small></label><label>Client secret<input required type="password" name="clientSecret" value="demo_client_secret" autocomplete="new-password" /><small>Stored securely and never shown again after you connect. Do not paste an Admin API access token here.</small></label><label class="portal-check portal-terms"><input required type="checkbox" checked /> <span>I created this app in Shopify Dev Dashboard and authorize BestCheckout to use it for this store.</span></label><button type="submit" class="portal-submit">Connect store ' + icon('arrow', 16) + '</button></form><aside class="connect-help"><span>' + icon('help', 16) + '</span><div><strong>Need to create your Shopify app?</strong><p>We will show the current Shopify path and where to find your Client ID and Client secret. Your app remains owned by your business.</p><a href="../help/#guide=connect-shopify" target="_blank" rel="noopener">View setup guide ' + icon('external', 14) + '</a></div></aside></div></main></div>';
}
