import { badge, button, icon, metricCard, pageHeader, sectionHeader } from '../components/common.js';
import { escapeHtml } from '../utils.js';

const ORDERS = [
  { id: 'BC-1048', shopify: '#1048', customer: 'Maya Coleman', email: 'maya@example.com', total: '$96.20', items: 'Sleep Reset Starter Kit + Nighttime Gummies', payment: 'Paid', sync: 'Synced to Shopify', time: 'Today, 10:42 AM', tone: 'success' },
  { id: 'BC-1047', shopify: '#1047', customer: 'Riley Thomas', email: 'riley@example.com', total: '$72.00', items: 'Sleep Reset Starter Kit', payment: 'Paid', sync: 'Sync in progress', time: 'Today, 10:17 AM', tone: 'warning' },
  { id: 'BC-1046', shopify: '#1046', customer: 'Avery Chen', email: 'avery@example.com', total: '$118.80', items: 'Sleep Reset Starter Kit + 2 offers', payment: 'Paid', sync: 'Synced to Shopify', time: 'Today, 9:54 AM', tone: 'success' },
  { id: 'BC-1045', shopify: '—', customer: 'Jordan Lee', email: 'jordan@example.com', total: '$64.00', items: 'Sleep Reset Starter Kit', payment: 'Paid', sync: 'Needs attention', time: 'Today, 9:21 AM', tone: 'critical' },
  { id: 'BC-1044', shopify: '#1044', customer: 'Morgan Patel', email: 'morgan@example.com', total: '$89.60', items: 'Sleep Reset Starter Kit + Travel size', payment: 'Paid', sync: 'Synced to Shopify', time: 'Yesterday, 6:35 PM', tone: 'success' },
];

function orderRow(order) {
  return '<tr><td><button type="button" class="order-link" data-route="orders/' + escapeHtml(order.id) + '">' + escapeHtml(order.id) + '</button><small>' + escapeHtml(order.time) + '</small></td><td><strong>' + escapeHtml(order.customer) + '</strong><small>' + escapeHtml(order.email) + '</small></td><td class="order-items">' + escapeHtml(order.items) + '</td><td class="num"><strong>' + escapeHtml(order.total) + '</strong></td><td>' + badge(order.payment) + '</td><td><span class="order-sync order-sync-' + order.tone + '"><i></i>' + escapeHtml(order.sync) + '</span><small>' + (order.shopify === '—' ? 'Shopify order not created yet' : 'Shopify ' + escapeHtml(order.shopify)) + '</small></td></tr>';
}

function renderDetail(order) {
  return '<div class="page-stack order-detail"><button type="button" class="back-link" data-route="orders">' + icon('back', 16) + '<span>Orders</span></button>' + pageHeader('Order ' + order.id, 'Paid through BestCheckout and continued in Shopify.', badge(order.sync)) + '<section class="order-detail-grid"><div class="card"><div class="card-pad">' + sectionHeader('Order summary', 'A final order snapshot preserves what the buyer paid.') + '<dl class="detail-grid"><div><dt>Customer</dt><dd>' + escapeHtml(order.customer) + '</dd></div><div><dt>Total paid</dt><dd>' + escapeHtml(order.total) + '</dd></div><div><dt>Payment status</dt><dd>' + badge(order.payment) + '</dd></div><div><dt>Shopify order</dt><dd>' + (order.shopify === '—' ? 'Not created yet' : escapeHtml(order.shopify)) + '</dd></div></dl><div class="order-line-items"><div><span>Sleep Reset Starter Kit</span><strong>$64.00</strong></div><div><span>Post-purchase offer</span><strong>$32.20</strong></div><div><b>Total</b><b>' + escapeHtml(order.total) + '</b></div></div></div></div><aside class="card"><div class="card-pad">' + sectionHeader('Order status', 'BestCheckout keeps payment and Shopify order status clear.') + '<ol class="order-timeline"><li class="is-complete"><span>' + icon('check', 14) + '</span><div><strong>Checkout completed</strong><small>Buyer completed payment in BestCheckout.</small></div><time>10:42 AM</time></li><li class="is-complete"><span>' + icon('check', 14) + '</span><div><strong>Payment confirmed</strong><small>Payment was captured successfully.</small></div><time>10:42 AM</time></li><li class="' + (order.tone === 'critical' ? 'is-attention' : 'is-complete') + '"><span>' + icon(order.tone === 'critical' ? 'alert' : 'check', 14) + '</span><div><strong>' + escapeHtml(order.sync) + '</strong><small>' + (order.tone === 'critical' ? 'We will retry automatically. You can also retry now.' : 'This order is available in Shopify for fulfillment.') + '</small></div><time>' + (order.tone === 'critical' ? 'Now' : '10:43 AM') + '</time></li></ol>' + (order.tone === 'critical' ? button('Retry Shopify sync', 'retry-order-sync', { kind: 'secondary', icon: 'sync' }) : button('Open in Shopify', 'open-shopify-order', { kind: 'secondary', icon: 'external' })) + '</div></aside></section></div>';
}

export function renderOrders(state, route) {
  const order = route.segments[1] ? ORDERS.find(function (item) { return item.id === route.segments[1]; }) : null;
  if (order) return renderDetail(order);
  const filter = state.ui.ordersFilter || 'all';
  const filtered = filter === 'attention' ? ORDERS.filter(function (item) { return item.tone === 'critical' || item.tone === 'warning'; }) : filter === 'synced' ? ORDERS.filter(function (item) { return item.tone === 'success'; }) : ORDERS;
  const filters = [['all', 'All orders'], ['attention', 'Needs attention'], ['synced', 'Synced to Shopify']].map(function (item) { return '<button type="button" class="filter-chip' + (item[0] === filter ? ' is-active' : '') + '" data-action="filter-orders" data-filter="' + item[0] + '">' + item[1] + '</button>'; }).join('');
  const header = pageHeader('Orders', 'Orders are created in BestCheckout after payment, then continue in Shopify for fulfillment.', button('View activity', 'open-orders-activity', { kind: 'secondary', icon: 'activity' }));
  return '<div class="page-stack">' + header + '<section class="metric-grid orders-metric-grid">' + metricCard('Paid orders today', { value: '84', delta: '+12%', helper: 'vs yesterday' }, 'orders') + metricCard('Sales through checkout', { value: '$7,241.60', delta: '+18%', helper: 'vs last week' }, 'analytics') + metricCard('Synced to Shopify', { value: '98.8%', delta: 'Healthy', helper: 'last 7 days' }, 'check') + metricCard('Needs attention', { value: '1', delta: 'Action needed', helper: 'paid order' }, 'alert') + '</section><section class="card"><div class="card-pad orders-table-head">' + sectionHeader('Recent orders', 'View payment and Shopify order status without switching between systems.') + '<div class="orders-filters">' + filters + '</div></div><div class="table-scroll"><table class="data-table orders-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th class="num">Total</th><th>Payment</th><th>Shopify status</th></tr></thead><tbody>' + filtered.map(orderRow).join('') + '</tbody></table></div></section></div>';
}
