import { badge, banner, button, icon, pageHeader, progressBar, routeButton, sectionHeader } from '../components/common.js';
import { SETTINGS_TABS } from '../type.js?rev=20260720-standalone-portal-v150';
import { escapeHtml } from '../utils.js';

function settingsTabs(active) {
  return '<nav class="settings-tabs" aria-label="Settings sections">' + SETTINGS_TABS.map(function (tab) {
    return '<button type="button" class="settings-tab' + (tab.id === active ? ' is-active' : '') + '" data-route="settings?tab=' + tab.id + '" aria-current="' + (tab.id === active ? 'page' : 'false') + '">' + escapeHtml(tab.label) + '</button>';
  }).join('') + '</nav>';
}

function renderConnection(state) {
  const store = state.store;
  const isZh = state.ui.locale === 'zh';
  const text = function (en, zh) { return isZh ? zh : en; };
  const ready = '<div class="merchant-connection-ready"><span>' + icon('check', 18) + '</span><div><strong>' + escapeHtml(text('Your Shopify store is ready for checkout', '你的 Shopify 店铺已可用于 Checkout')) + '</strong><small>' + escapeHtml(text('Products, prices, discounts and delivery rates stay current automatically.', '商品、价格、促销与配送规则会自动保持最新。')) + '</small></div></div>';
  const facts = '<dl class="detail-grid merchant-connection-facts"><div><dt>Shopify</dt><dd data-i18n-skip>' + escapeHtml(store.myshopifyDomain) + '</dd></div><div><dt>' + escapeHtml(text('Store data', '店铺数据')) + '</dt><dd>' + badge('Ready', text('Ready', '已就绪')) + '</dd></div><div><dt>' + escapeHtml(text('Last updated', '最近更新')) + '</dt><dd>' + escapeHtml(store.lastSync) + '</dd></div><div><dt>' + escapeHtml(text('Store access', '店铺访问')) + '</dt><dd>' + badge('Connected', text('Connected', '已连接')) + '</dd></div></dl>';
  const help = '<aside class="card merchant-connection-help"><div class="card-pad"><span class="eyebrow">' + escapeHtml(text('Need help?', '需要帮助？')) + '</span><h2>' + escapeHtml(text('Keep your checkout data ready', '保持 Checkout 数据随时可用')) + '</h2><p>' + escapeHtml(text('BestCheckout refreshes the store data needed by your checkout in the background. You only need to revisit this page if we ask you to reconnect Shopify.', 'BestCheckout 会在后台更新 Checkout 所需的店铺数据。只有在系统提示时，才需要重新连接 Shopify。')) + '</p>' + button(text('Contact support', '联系支持'), 'contact-sync-support', { kind: 'secondary', icon: 'user' }) + '</div></aside>';
  return '<div class="settings-stack">'
    + banner('success', text('Shopify is connected', 'Shopify 已连接'), text('BestCheckout keeps the store data required for your checkout ready in the background.', 'BestCheckout 会在后台保持 Checkout 所需的店铺数据可用。'))
    + '<section class="settings-two-col"><div class="card"><div class="card-pad">' + sectionHeader(text('Store status', '店铺状态'), text('Everything your checkout needs from this Shopify store.', '当前 Shopify 店铺为 Checkout 提供的必要数据。')) + ready + facts + '</div></div>' + help + '</section>'
    + '<section class="card"><div class="card-pad">' + sectionHeader(text('Automatic updates', '自动更新'), text('No routine action is needed from you.', '无需进行日常操作。')) + '<div class="merchant-connection-steps"><div><span>1</span><strong>' + escapeHtml(text('Shopify changes', 'Shopify 发生变更')) + '</strong><small>' + escapeHtml(text('Product, price and delivery changes are detected automatically.', '系统会自动识别商品、价格与配送变更。')) + '</small></div><div><span>2</span><strong>BestCheckout</strong><small>' + escapeHtml(text('Keeps checkout data current in the background.', '在后台更新 Checkout 所需的数据。')) + '</small></div><div><span>3</span><strong>' + escapeHtml(text('Keep selling', '继续销售')) + '</strong><small>' + escapeHtml(text('Your purchase flows use the latest eligible data.', '购买流程持续使用最新的可用数据。')) + '</small></div></div></div></section></div>';
}

function renderEmails(state) {
  const isZh = state.ui.locale === 'zh';
  const text = function (en, zh) { return isZh ? zh : en; };
  const emails = [
    { name: text('Order confirmation', '订单确认'), detail: text('Sent after payment is confirmed, including accepted post-purchase items.', '付款确认后发送，包含已接受的购后加购商品。'), state: text('On', '已开启') },
    { name: text('Payment receipt', '付款收据'), detail: text('Gives buyers a clear record of the payment captured by BestCheckout.', '向买家提供 BestCheckout 收款成功的清晰凭证。'), state: text('On', '已开启') },
    { name: text('Abandoned checkout reminder', '未完成结账提醒'), detail: text('Optional recovery message for buyers who leave before payment.', '向付款前离开的买家发送可选的挽回提醒。'), state: text('Draft', '草稿') },
  ].map(function (item) { return '<article class="checkout-email-card"><span>' + icon('email', 18) + '</span><div><strong>' + escapeHtml(item.name) + '</strong><p>' + escapeHtml(item.detail) + '</p></div><em>' + escapeHtml(item.state) + '</em><button type="button" class="button button-secondary" data-action="edit-checkout-email">' + escapeHtml(text('Customize', '自定义')) + '</button></article>'; }).join('');
  return '<div class="settings-stack">'
    + banner('info', text('Emails use your checkout brand', '邮件沿用你的 Checkout 品牌'), text('Logo, colors and sender details are shared with your checkout pages so buyers recognize every message.', 'Logo、颜色与发件信息会与 Checkout 页面保持一致，让买家能够识别每一封邮件。'))
    + '<section class="settings-two-col"><div class="card"><div class="card-pad">' + sectionHeader(text('Sender details', '发件信息'), text('Shown on every buyer email from BestCheckout.', '会显示在 BestCheckout 发送给买家的每封邮件中。'), button(text('Edit sender', '编辑发件人'), 'edit-checkout-email', { kind: 'secondary' })) + '<dl class="detail-grid detail-grid-single"><div><dt>' + escapeHtml(text('Sender name', '发件人名称')) + '</dt><dd>Lavender Labs</dd></div><div><dt>' + escapeHtml(text('Reply-to email', '回复邮箱')) + '</dt><dd>support@lavenderlabs.co</dd></div></dl></div></div><aside class="card"><div class="card-pad">' + sectionHeader(text('Shared checkout style', '共享 Checkout 样式'), text('Email styles come from your checkout brand settings.', '邮件样式来自 Checkout 品牌设置。')) + '<div class="email-brand-preview"><span class="bestcheckout-mark">L</span><div><strong>Lavender Labs</strong><small>' + escapeHtml(text('Order update', '订单更新')) + '</small></div></div><button type="button" class="button button-plain" data-route="pages">' + escapeHtml(text('Edit checkout pages', '编辑 Checkout 页面')) + '</button></div></aside></section>'
    + '<section class="card"><div class="card-pad">' + sectionHeader(text('Buyer emails', '买家邮件'), text('Turn on only the messages that help buyers complete or understand their order.', '仅开启能帮助买家完成或了解订单的消息。')) + '<div class="checkout-email-list">' + emails + '</div></div></section></div>';
}

function renderSync(state) {
  const store = state.store;
  const isZh = state.ui.locale === 'zh';
  const text = function (en, zh) { return isZh ? zh : en; };
  const stats = [
    [text('Products', '商品'), store.products, 'products'],
    [text('Variants', '变体'), store.variants, 'products'],
    [text('Discounts', '促销'), store.discounts, 'products'],
    [text('Shipping rates', '运费规则'), store.shippingRates, 'store'],
  ].map(function (item) {
    return '<div class="sync-stat"><span class="sync-stat-icon">' + icon(item[2], 17) + '</span><div><strong>' + escapeHtml(item[1]) + '</strong><small>' + escapeHtml(item[0]) + '</small></div></div>';
  }).join('');
  const history = [
    [text('Shopify access authorized', 'Shopify 授权完成'), text('Scopes verified for products, discounts, shipping and orders.', '商品、促销、运费与订单权限已通过校验。'), '09:31'],
    [text('Checkout workspace created', 'Checkout 工作区已创建'), text('Store, currency and market defaults provisioned.', '已创建店铺、币种与市场默认配置。'), '09:32'],
    [text('Initial commerce data imported', '初始商业数据已同步'), text('Products, variants, promotions and rates were mapped.', '商品、变体、促销与运费规则已完成映射。'), '09:36'],
    [text('Webhook subscriptions registered', 'Webhook 订阅已注册'), text('12 topics are active with signature verification.', '12 个主题已启用签名校验。'), '09:37'],
  ].map(function (item) {
    return '<li class="is-complete"><span>' + icon('check', 14) + '</span><div><strong>' + escapeHtml(item[0]) + '</strong><small>' + escapeHtml(item[1]) + '</small></div><time>' + item[2] + '</time></li>';
  }).join('');
  const installation = '<section class="card installation-card"><div class="card-pad"><div class="installation-card-head"><div><span class="eyebrow">' + escapeHtml(text('Shopify installation', 'Shopify 安装')) + '</span><h2>' + escapeHtml(text('This store’s App instance', '当前店铺的 App 实例')) + '</h2><p>' + escapeHtml(text('BestCheckout uses a merchant-specific Custom-distribution App. This store keeps its own authorization and runtime configuration.', 'BestCheckout 通过商户专属的 Custom distribution App 安装；当前店铺拥有独立授权与运行时配置。')) + '</p></div>' + badge('Complete', text('Installed', '已安装')) + '</div><div class="installation-instance"><span>' + icon('shield', 19) + '</span><div><small>' + escapeHtml(text('Shopify App instance', 'Shopify App 实例')) + '</small><strong data-i18n-skip>' + escapeHtml(store.appInstanceName) + '</strong><code data-i18n-skip>' + escapeHtml(store.appInstanceId) + '</code></div><em>' + escapeHtml(store.distributionMethod) + '</em></div><div class="installation-facts"><div><small>' + escapeHtml(text('Installation scope', '安装范围')) + '</small><strong>' + escapeHtml(text('This store only', '当前店铺')) + '</strong></div><div><small>' + escapeHtml(text('Install source', '安装入口')) + '</small><strong>' + escapeHtml(text('Organization-specific link', '组织专属安装链接')) + '</strong></div><div><small>' + escapeHtml(text('Store authorization', '店铺授权')) + '</small><strong>' + escapeHtml(text('Connected', '已连接')) + '</strong></div></div><button type="button" class="button button-secondary" data-action="show-installation">' + icon('flow', 16) + '<span>' + escapeHtml(text('View installation method', '查看安装方式')) + '</span></button></div></section>';
  return '<div class="settings-stack">'
    + banner('success', text('Store data is synchronized', '店铺数据已同步'), text('BestCheckout created the checkout workspace, mapped Shopify IDs and registered webhooks during authorization.', '授权后，BestCheckout 已自动创建 Checkout 工作区、映射 Shopify ID 并注册 Webhook。'), button(text('Sync now', '立即同步'), 'sync-store', { kind: 'plain', icon: 'sync' }))
    + '<section class="card"><div class="card-pad">' + sectionHeader(text('Shopify connection', 'Shopify 连接'), store.myshopifyDomain, badge(store.status, text('Connected', '已连接'))) + '<dl class="detail-grid"><div><dt>' + escapeHtml(text('Checkout workspace', 'Checkout 工作区')) + '</dt><dd>' + escapeHtml(text('Provisioned', '已开通')) + '</dd></div><div><dt>' + escapeHtml(text('Mapping coverage', '映射覆盖率')) + '</dt><dd>' + escapeHtml(store.mappingCoverage) + '</dd></div><div><dt>' + escapeHtml(text('Webhook health', 'Webhook 健康度')) + '</dt><dd>' + escapeHtml(store.webhookHealth) + '</dd></div><div><dt>' + escapeHtml(text('Last successful sync', '最近同步')) + '</dt><dd>' + escapeHtml(store.lastSync) + '</dd></div></dl><div class="sync-stats">' + stats + '</div></div></section>'
    + installation
    + '<section class="settings-two-col"><div class="card"><div class="card-pad">' + sectionHeader(text('Automatic setup history', '自动开通记录'), text('Completed automatically after Shopify authorization.', '以下步骤在 Shopify 授权后由系统自动完成。')) + '<ol class="setup-history">' + history + '</ol></div></div><aside class="card"><div class="card-pad">' + sectionHeader(text('ID mapping health', 'ID 映射健康度'), text('Shopify IDs stay as the source reference while mapped IDs power checkout execution.', 'Shopify ID 保持为来源参考，映射后的 ID 用于 Checkout 运行。')) + '<div class="mapping-health"><strong>100%</strong><span>' + escapeHtml(store.variants + ' / ' + store.variants + ' ' + text('active variants mapped', '个活跃变体已映射')) + '</span>' + progressBar(100, 'success') + '</div><div class="mapping-list"><div><span>' + escapeHtml(text('Missing products', '缺失商品')) + '</span><strong>0</strong></div><div><span>' + escapeHtml(text('Stale variants', '过期变体')) + '</span><strong>0</strong></div><div><span>' + escapeHtml(text('Webhook backlog', 'Webhook 积压')) + '</span><strong>0</strong></div></div><button type="button" class="button button-secondary button-block" data-action="download-mapping-report">' + escapeHtml(text('Download mapping report', '下载映射报告')) + '</button></div></aside></section></div>';
}

function renderDomainLegacy(state) {
  const store = state.store;
  const host = store.domain.split('.')[0] || 'checkout';
  const rootDomain = store.domain.split('.').slice(1).join('.') || 'yourstore.com';
  return '<div class="settings-stack"><section class="card domain-hero"><div class="card-pad"><div class="domain-hero-top"><span class="domain-icon">' + icon('globe', 24) + '</span><div><span class="eyebrow">Checkout domain</span><h2 data-i18n-skip>' + escapeHtml(store.domain) + '</h2><p>This is the address buyers see when they move from your store to checkout.</p></div>' + badge(store.domainStatus) + '</div><div class="domain-setup"><div class="domain-setup-head"><div><strong>Connect your checkout subdomain</strong><small>Add this record with the company that manages ' + escapeHtml(rootDomain) + '.</small></div>' + button('Change domain', 'change-domain', { kind: 'plain' }) + '</div><div class="dns-record"><div><small>Record type</small><strong>CNAME</strong></div><div><small>Host / name</small><code data-i18n-skip>' + escapeHtml(host) + '</code></div><div><small>Points to</small><code data-i18n-skip>shops.bestcheckout.app</code></div><div><small>TTL</small><strong>Auto</strong></div><button type="button" class="button button-secondary" data-action="copy-dns-record">' + icon('copy', 16) + '<span>Copy record</span></button></div><ol class="numbered-steps domain-steps"><li><span>1</span><div><strong>Add the CNAME record</strong><small>Use the host and target shown above in your DNS provider.</small></div></li><li><span>2</span><div><strong>Wait for DNS to update</strong><small>This can take a few minutes, depending on your DNS provider.</small></div></li><li><span>3</span><div><strong>Verify your domain</strong><small>BestCheckout will enable SSL after the record is found.</small></div></li></ol></div><div class="inline-actions">' + button('Verify DNS', 'verify-domain', { icon: 'sync' }) + '</div></div></section><section class="card"><div class="card-pad">' + sectionHeader('Checkout address', 'Buyers start on your Shopify store and continue on your branded checkout domain.') + '<div class="url-pattern"><span>Shopify store</span><code data-i18n-skip>https://www.lavenderlabs.co/cart</code><i>' + icon('arrow', 17) + '</i><span>Buyer checkout</span><code data-i18n-skip>https://' + escapeHtml(store.domain) + '/c/••••</code></div></div></section></div>';
}

function renderDomain(state) {
  const store = state.store;
  const isZh = state.ui.locale === 'zh';
  const host = store.domain.split('.')[0] || 'checkout';
  const rootDomain = store.domain.split('.').slice(1).join('.') || 'yourstore.com';
  const manual = state.ui.domainSetupMode === 'manual';
  const provider = store.dnsProvider || 'Cloudflare';
  const connection = store.domainConnection || 'Not connected';
  const automaticPath = '<article class="setup-path setup-path-recommended"><header><span class="setup-path-icon">' + icon('sparkles', 18) + '</span><div><strong>Connect your DNS provider</strong><small>Recommended · no record copying</small></div><em>Recommended</em></header><p>Sign in to your DNS provider once. BestCheckout adds this checkout record, monitors DNS and provisions SSL automatically.</p><div class="setup-path-meta"><span>' + icon('shield', 15) + ' Provider access is limited to this record</span><span>' + icon('check', 15) + ' SSL is issued automatically</span></div>' + button(connection === 'Connected' ? 'Manage provider connection' : 'Connect DNS provider', 'connect-dns-provider', { kind: 'primary', icon: 'external' }) + '</article>';
  const manualPath = '<article class="setup-path"><header><span class="setup-path-icon">' + icon('settings', 18) + '</span><div><strong>Add a DNS record yourself</strong><small>Use this when your provider is not available for secure connection.</small></div></header><p>You only need to add one CNAME record. BestCheckout keeps checking and creates SSL as soon as it is found.</p>' + button('Show CNAME record', 'show-manual-domain-setup', { kind: 'secondary', icon: 'settings' }) + '</article>';
  const manualDetails = '<div class="manual-domain-details"><div class="dns-record"><div><small>Record type</small><strong>CNAME</strong></div><div><small>Host / name</small><code data-i18n-skip>' + escapeHtml(host) + '</code></div><div><small>Points to</small><code data-i18n-skip>shops.bestcheckout.app</code></div><div><small>TTL</small><strong>Auto</strong></div><button type="button" class="button button-secondary" data-action="copy-dns-record">' + icon('copy', 16) + '<span>Copy record</span></button></div><p class="helper-copy">Paste this record in the service that manages <strong data-i18n-skip>' + escapeHtml(rootDomain) + '</strong>. You do not need to configure certificates or callbacks.</p></div>';
  const connectionState = connection === 'Connected'
    ? '<div class="domain-connected-status">' + icon('check', 16) + '<span><strong>' + escapeHtml(provider) + ' is connected</strong><small>BestCheckout is monitoring DNS and SSL for ' + escapeHtml(store.domain) + '.</small></span></div>'
    : '';
  return '<div class="settings-stack"><section class="card domain-hero"><div class="card-pad"><div class="domain-hero-top"><span class="domain-icon">' + icon('globe', 24) + '</span><div><span class="eyebrow">' + (isZh ? 'Checkout 域名' : 'Checkout domain') + '</span><h2 data-i18n-skip>' + escapeHtml(store.domain) + '</h2><p>' + (isZh ? '这是买家从店铺进入 Checkout 时看到的地址。' : 'This is the address buyers see when they move from your store to checkout.') + '</p></div>' + badge(store.domainStatus) + '</div><div class="setup-assist"><span>' + icon('play', 17) + '</span><div><strong>Keep building while your domain is being connected</strong><small>' + (isZh ? '使用 ' : 'Use ') + '<code data-i18n-skip>' + escapeHtml(store.previewDomain || 'lavender-labs.preview.bestcheckout.app') + '</code>' + (isZh ? ' 进行安全预览。只有开始向真实买家分配流量前，才必须完成品牌域名解析。' : ' for safe previews. Branded DNS is required only before sending live traffic.') + '</small></div><button type="button" class="button button-plain" data-action="copy-preview-domain">Copy preview address</button></div><div class="domain-setup"><div class="domain-setup-head"><div><strong>' + (isZh ? '连接 ' + escapeHtml(rootDomain) + ' 的域名' : 'Choose how to connect ' + escapeHtml(rootDomain)) + '</strong><small>Most merchants finish the only required action by securely authorizing their DNS provider.</small></div>' + button('Change domain', 'change-domain', { kind: 'plain' }) + '</div><div class="setup-path-grid">' + automaticPath + manualPath + '</div>' + (manual ? manualDetails : '') + connectionState + '<div class="inline-actions">' + button(store.domainStatus === 'Verified' ? 'DNS verified' : 'Check connection', 'verify-domain', { icon: 'sync', kind: store.domainStatus === 'Verified' ? 'secondary' : 'primary' }) + (manual ? button('Use automatic setup instead', 'show-automatic-domain-setup', { kind: 'plain' }) : '') + '</div></div></div></section><section class="card"><div class="card-pad">' + sectionHeader(isZh ? '买家看到的地址' : 'Checkout address', isZh ? '买家从 Shopify 店铺出发，并在你的品牌 Checkout 域名中完成结账。' : 'Buyers start on your Shopify store and continue on your branded checkout domain.') + '<div class="url-pattern"><span>' + (isZh ? 'Shopify 店铺' : 'Shopify store') + '</span><code data-i18n-skip>https://www.lavenderlabs.co/cart</code><i>' + icon('arrow', 17) + '</i><span>' + (isZh ? '买家 Checkout' : 'Buyer checkout') + '</span><code data-i18n-skip>https://' + escapeHtml(store.domain) + '/c/••••</code></div></div></section></div>';
}

function capabilityBadge(value) {
  return badge(value);
}

function renderPaymentsLegacy(state) {
  const providerCards = state.providers.map(function (provider) {
    const actionLabel = provider.status === 'Connected' ? 'Manage' : 'Join waitlist';
    const action = provider.status === 'Connected' ? 'manage-provider' : 'waitlist-provider';
    return '<article class="provider-card"><header><span class="provider-logo provider-' + escapeHtml(provider.id) + '" data-i18n-skip>' + escapeHtml(provider.name.charAt(0)) + '</span><div data-i18n-skip><strong>' + escapeHtml(provider.name) + '</strong><small>' + escapeHtml(provider.account) + '</small></div>' + badge(provider.status) + '</header><dl><div><dt>Payment methods</dt><dd>' + escapeHtml(provider.methods) + '</dd></div><div><dt>Regions</dt><dd>' + escapeHtml(provider.regions) + '</dd></div><div><dt>Post-purchase summary</dt><dd>' + capabilityBadge(provider.postPurchase) + '</dd></div><div><dt>Last 30 days</dt><dd>' + escapeHtml(provider.capabilityCoverage) + '</dd></div></dl><p>' + escapeHtml(provider.notes) + '</p><footer><span>' + (provider.successRate === '—' ? 'Not processing traffic' : escapeHtml(provider.successRate) + ' payment success') + '</span><button type="button" class="button button-plain" data-action="' + action + '" data-provider-id="' + escapeHtml(provider.id) + '">' + escapeHtml(actionLabel) + '</button></footer></article>';
  }).join('');
  const rows = state.providers.flatMap(function (provider) {
    return provider.capabilityEvaluations.map(function (evaluation) {
      const connection = evaluation.authorizationState === 'Secure authorization verified' ? 'Connected' : evaluation.authorizationState;
      return '<tr><td><strong data-i18n-skip>' + escapeHtml(provider.name) + '</strong></td><td>' + escapeHtml(evaluation.method) + '</td><td>' + escapeHtml(evaluation.region + ' · ' + evaluation.currency) + '</td><td>' + escapeHtml(connection) + '</td><td>' + capabilityBadge(evaluation.outcome) + '</td><td>' + escapeHtml(evaluation.confirmationFlow) + '</td></tr>';
    });
  }).join('');
  return '<div class="settings-stack">' + banner('info', 'Post-purchase eligibility is evaluated per transaction', 'Unsupported methods and failures before an additional charge are safe skips. After an additional charge succeeds, snapshot or writeback failures enter reconciliation and must not be skipped.', button('View runtime rules', 'show-capability-rules', { kind: 'plain' })) + '<section><div class="section-header outside-card"><div><h2>Payment providers</h2><p>BestCheckout stores secure connection references, never raw card data or copied Shopify credentials.</p></div>' + button('Connect provider', 'connect-provider', { kind: 'primary', icon: 'plus' }) + '</div><div class="provider-grid">' + providerCards + '</div></section><section class="card"><div class="card-pad">' + sectionHeader('Capability evaluations', 'Provider connection alone never proves post-purchase support; the backend evaluates the concrete transaction combination.') + '</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Provider</th><th>Method</th><th>Market</th><th>Authorization</th><th>Outcome</th><th>Confirmation</th><th>Reason</th></tr></thead><tbody>' + rows + '</tbody></table></div></section></div>';
}

function renderPayments(state) {
  const isZh = state.ui.locale === 'zh';
  const providerCards = state.providers.map(function (provider) {
    const connectable = provider.status === 'Action required';
    const actionLabel = provider.status === 'Connected' ? (isZh ? '管理连接' : 'Manage connection') : connectable ? (isZh ? '连接账户' : 'Connect account') : (isZh ? '加入等候名单' : 'Join waitlist');
    const action = provider.status === 'Connected' ? 'manage-provider' : connectable ? 'connect-provider' : 'waitlist-provider';
    const account = provider.account === 'Not connected' && isZh ? '未连接' : provider.account;
    const coverage = provider.capabilityCoverage === 'Connect an account to evaluate' && isZh ? '连接账户后评估' : provider.capabilityCoverage;
    const processing = provider.successRate === '—' ? (isZh ? '尚未处理流量' : 'Not processing traffic') : escapeHtml(provider.successRate) + (isZh ? ' 支付成功率' : ' payment success');
    return '<article class="provider-card"><header><span class="provider-logo provider-' + escapeHtml(provider.id) + '" data-i18n-skip>' + escapeHtml(provider.name.charAt(0)) + '</span><div data-i18n-skip><strong>' + escapeHtml(provider.name) + '</strong><small>' + escapeHtml(account) + '</small></div>' + badge(provider.status) + '</header><dl><div><dt>Payment methods</dt><dd>' + escapeHtml(provider.methods) + '</dd></div><div><dt>Regions</dt><dd>' + escapeHtml(provider.regions) + '</dd></div><div><dt>Post-purchase summary</dt><dd>' + capabilityBadge(provider.postPurchase) + '</dd></div><div><dt>Last 30 days</dt><dd>' + escapeHtml(coverage) + '</dd></div></dl><p>' + escapeHtml(provider.notes) + '</p><footer><span>' + processing + '</span><button type="button" class="button button-plain" data-action="' + action + '" data-provider-id="' + escapeHtml(provider.id) + '">' + escapeHtml(actionLabel) + '</button></footer></article>';
  }).join('');
  const rows = state.providers.flatMap(function (provider) {
    return provider.capabilityEvaluations.map(function (evaluation) {
      const connection = evaluation.authorizationState === 'Secure authorization verified' ? 'Connected' : evaluation.authorizationState;
      return '<tr><td><strong data-i18n-skip>' + escapeHtml(provider.name) + '</strong></td><td>' + escapeHtml(evaluation.method) + '</td><td>' + escapeHtml(evaluation.region + ' · ' + evaluation.currency) + '</td><td>' + escapeHtml(connection) + '</td><td>' + capabilityBadge(evaluation.outcome) + '</td><td>' + escapeHtml(evaluation.confirmationFlow) + '</td></tr>';
    });
  }).join('');
  const setup = '<section class="card payment-setup"><div class="card-pad"><div class="payment-setup-head"><div><span class="eyebrow">Fast setup</span><h2>Connect a payment account with a guided setup</h2><p>Use secure authorization when your payment provider supports it. Otherwise, BestCheckout requests only the connection detail it needs, then checks that payments are ready before you launch.</p></div>' + button('Connect payment account', 'connect-provider', { kind: 'primary', icon: 'plus' }) + '</div><div class="connection-flow"><div><span>1</span><strong>Choose a provider</strong><small>Select the account that receives your checkout payments.</small></div><i>' + icon('arrow', 17) + '</i><div><span>2</span><strong>Connect your account</strong><small>Authorize BestCheckout or add the one required connection detail.</small></div><i>' + icon('arrow', 17) + '</i><div><span>3</span><strong>Confirm checkout is ready</strong><small>BestCheckout checks available payment methods and prepares a safe test.</small></div></div><p class="payment-setup-footnote">You never need to configure technical callback addresses or signatures. If a provider needs a credential, BestCheckout asks only for the required one and keeps it protected.</p></div></section>';
  return '<div class="settings-stack">' + setup + banner('info', 'Buyer offers are checked for every order', 'If a payment method cannot support an additional offer, the buyer simply continues with their original order. Their completed payment is always preserved.', button('Learn about offers', 'show-capability-rules', { kind: 'plain' })) + '<section><div class="section-header outside-card"><div><h2>Payment providers</h2><p>See which payment methods and buyer offers are ready for each connected account.</p></div>' + button('Connect provider', 'connect-provider', { kind: 'primary', icon: 'plus' }) + '</div><div class="provider-grid">' + providerCards + '</div></section><section class="card"><div class="card-pad">' + sectionHeader('Payment availability', 'Availability can vary by the buyer\'s payment method, market and order.') + '</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Provider</th><th>Payment method</th><th>Market</th><th>Connection</th><th>Buyer offers</th><th>Next step</th></tr></thead><tbody>' + rows + '</tbody></table></div></section></div>';
}

function renderAttribution(state) {
  const rows = state.tracking.map(function (item) {
    return '<tr><td><div class="tracking-name"><span class="tracking-icon">' + icon(item.id === 'bestcheckout' ? 'sparkles' : 'pixel', 16) + '</span><div data-i18n-skip><strong>' + escapeHtml(item.name) + '</strong><small>' + escapeHtml(item.discoveredId + ' · ' + item.discoveredFrom) + '</small></div></div></td><td>' + escapeHtml(item.ownershipState) + '</td><td>' + escapeHtml(item.browserConfigState) + '</td><td>' + escapeHtml(item.serverAuthState) + '</td><td>' + escapeHtml(item.consentState) + '</td><td>' + escapeHtml(item.testState) + '</td><td>' + badge(item.state) + '</td></tr>';
  }).join('');
  return '<div class="settings-stack">' + banner('warning', 'Confirm every destination before tracking sales', 'BestCheckout found Meta, GA4 and GTM tags on your storefront. Choose the destinations you use, confirm consent requirements, and run a test before relying on their purchase data.', button('Review destinations', 'review-tags', { kind: 'plain' })) + '<section class="card"><div class="card-pad">' + sectionHeader('Sales tracking', 'Keep website tracking, server tracking and consent settings clear for every destination.', button('Run event test', 'run-event-test', { icon: 'play' })) + '</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Destination</th><th>Confirmed</th><th>Website tracking</th><th>Server tracking</th><th>Customer consent</th><th>Test</th><th>Status</th></tr></thead><tbody>' + rows + '</tbody></table></div></section><section class="card"><div class="card-pad">' + sectionHeader('How purchase data is shared', 'BestCheckout keeps the purchase journey connected from your Shopify storefront to the tools you choose.') + '<div class="attribution-flow"><div><span>' + icon('store', 19) + '</span><strong>Shopify storefront</strong><small>Campaign source · buyer consent</small></div><i>' + icon('arrow', 18) + '</i><div><span>' + icon('card', 19) + '</span><strong>BestCheckout</strong><small>Purchase flow · payment</small></div><i>' + icon('arrow', 18) + '</i><div><span>' + icon('orders', 19) + '</span><strong>Completed order</strong><small>Revenue · buyer offers · channel</small></div><i>' + icon('arrow', 18) + '</i><div><span>' + icon('pixel', 19) + '</span><strong>Your destinations</strong><small>Website and server events kept in sync</small></div></div><div class="contract-list"><div><strong>One completed-order event</strong><span>Purchase data is sent only after the buyer\'s final order is complete.</span></div><div><strong>Consistent sales reporting</strong><span>Website and server events work together to avoid counting the same order twice.</span></div><div><strong>Consent is respected</strong><span>Buyer consent is carried through the purchase journey before data is shared.</span></div></div></div></section></div>';
}

function renderEmbed(state) {
  const store = state.store;
  const entryChecks = store.embedEntryChecks.map(function (item) {
    return '<div class="guardrail-row"><span>' + escapeHtml(item.target) + '</span>' + badge(item.state) + '</div>';
  }).join('');
  return '<div class="settings-stack">' + banner('success', 'BestCheckout is enabled on your active theme', 'When you change or publish a theme, come back here and verify it again.', button('Verify again', 'verify-app-embed', { kind: 'plain', icon: 'sync' })) + '<section class="settings-two-col"><div class="card"><div class="card-pad">' + sectionHeader('Current theme', 'BestCheckout is currently connected to this Shopify theme.') + '<dl class="detail-grid detail-grid-single"><div><dt>Active theme</dt><dd data-i18n-skip>' + escapeHtml(store.activeTheme) + '</dd></div><div><dt>BestCheckout status</dt><dd>' + badge(store.appEmbed) + '</dd></div><div><dt>Last verified</dt><dd>' + escapeHtml(store.embedVerifiedAt) + '</dd></div></dl><button type="button" class="button button-secondary" data-action="open-theme-editor">' + icon('external', 16) + '<span>Open Shopify Theme Editor</span></button></div></div><aside class="card"><div class="card-pad">' + sectionHeader('How to enable BestCheckout', 'You only need to do this once for each new theme.') + '<ol class="numbered-steps"><li><span>1</span><div><strong>Open Online Store → Themes</strong><small>Customize the theme you want to use.</small></div></li><li><span>2</span><div><strong>Open App embeds</strong><small>Find BestCheckout in the left panel.</small></div></li><li><span>3</span><div><strong>Turn on BestCheckout and save</strong><small>Return here and choose Verify again.</small></div></li></ol></div></aside></section><section class="card"><div class="card-pad">' + sectionHeader('Supported checkout buttons', 'These storefront buttons are ready for your current theme.') + '<div class="guardrail-list">' + entryChecks + '</div></div></section></div>';
}

function renderDiagnostics(state) {
  const store = state.store;
  const isZh = state.ui.locale === 'zh';
  const text = function (en, zh) { return isZh ? zh : en; };
  const customerConditionsAvailable = store.customerConditionsAvailable !== false;
  const checks = [
    ['Shopify store connection', 'Healthy', 'Products, discounts and shipping rates are available for your checkout.'],
    ['Checkout domain', 'Verified', 'Your buyer checkout address is verified and protected.'],
    ['Payment accounts', 'Healthy', 'Your connected payment accounts are ready for checkout.'],
    ['Buyer offers', 'Healthy', 'Offer availability is checked for each buyer before it is shown.'],
    ['Sales tracking', 'Action required', 'Review Meta server tracking and Google Tag Manager consent settings.'],
    ['Orders sent to Shopify', 'Healthy', store.writebackCreateSuccessRate + '% of paid orders reached Shopify successfully.'],
    ['Storefront connection', 'Verified', 'Your active Shopify storefront is ready to send buyers to BestCheckout.'],
    [text('Customer conditions', '客户条件'), customerConditionsAvailable ? 'Available' : 'Action required', customerConditionsAvailable
      ? text('Ready for recognized customers. Buyers who cannot be recognized or do not match still use Shopify Checkout.', '已识别客户可使用客户条件；无法识别或不符合条件的买家会继续使用 Shopify Checkout。')
      : text('Customer conditions are not available for this store. Use cart or market conditions instead.', '当前店铺暂不能使用客户条件；可改用购物车或市场条件。')],
  ].map(function (item) {
    const label = item[1] === 'Available' ? text('Available', '可用') : (item[1] === 'Action required' ? text('Action required', '需处理') : item[1]);
    return '<div class="diagnostic-row"><span class="diagnostic-state">' + icon(['Action required', 'Open', 'Blocked'].includes(item[1]) ? 'alert' : 'check', 15) + '</span><div><strong>' + escapeHtml(item[0]) + '</strong><small>' + escapeHtml(item[2]) + '</small></div>' + badge(item[1], label) + '</div>';
  }).join('');
  const diagnosticActions = '<div class="inline-actions">' + button('Run health check', 'run-diagnostics', { kind: 'primary', icon: 'play' }) + '</div>';
  return '<div class="settings-stack"><section class="card"><div class="card-pad">' + sectionHeader('Store health', 'Last checked: ' + state.ui.diagnosticsRanAt, diagnosticActions) + '<div class="diagnostic-list">' + checks + '</div></div></section></div>';
}

export function renderSettings(state, route) {
  const requested = route.query.get('tab') || 'store';
  const active = SETTINGS_TABS.some(function (tab) { return tab.id === requested; }) ? requested : 'store';
  const header = pageHeader('Settings', 'Manage your store connection, buyer-facing checkout and order communication.');
  let content = renderConnection(state);
  if (active === 'domain') content = renderDomain(state);
  if (active === 'payments') content = renderPayments(state);
  if (active === 'emails') content = renderEmails(state);
  if (active === 'tracking') content = renderAttribution(state);
  if (active === 'diagnostics') content = renderDiagnostics(state);
  return '<div class="page-stack">' + header + settingsTabs(active) + content + '</div>';
}
